# Фильмы
## Получить список фильмов
GET http://localhost:5000/films/ HTTP/1.1
Content-Type: application/json

###

## Получить фильм по Id
GET http://localhost:5000/films/6491f4743ee80ff08a87a97d HTTP/1.1
Content-Type: application/json

###

## Получить промо-фильм
GET http://localhost:5000/films/promo HTTP/1.1
Content-Type: application/json

###

## Получить список фильмов одного жанра
POST http://localhost:5000/films/genre?limit=30 HTTP/1.1
Content-Type: application/json

{
  "genre": "Documentary"
}

###

## Получить список избранных фильмов
GET http://localhost:5000/films/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAbG9zdC5sb2NhIiwiaWQiOiI2NDkxZWI3NzY3N2Q4N2Y0OTQ2NjQ1MmQiLCJpYXQiOjE2ODcyODQ2OTksImV4cCI6MTY4NzQ1NzQ5OX0.tc9P6_EtDMT9oxz-juHyQ9ZHMFpkE7EckmV-GsDGOWM
###

## Добавить или удалить фильм в избранное
PATCH http://localhost:5000/films/favorite/6491eb77677d87f49466452a HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAbG9zdC5sb2NhIiwiaWQiOiI2NDkxZWI3NzY3N2Q4N2Y0OTQ2NjQ1MmQiLCJpYXQiOjE2ODcyODQ2OTksImV4cCI6MTY4NzQ1NzQ5OX0.tc9P6_EtDMT9oxz-juHyQ9ZHMFpkE7EckmV-GsDGOWM
###

## Добавить фильм
POST http://localhost:5000/films/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5saGkiLCJpZCI6IjY0OGM3ODY3MjgzNzAyZjE1YTA1MGFhZCIsImlhdCI6MTY4NzI3NzkxNywiZXhwIjoxNjg3NDUwNzE3fQ.7zHZzY_sDJraxLqW79YbUBIBTj27TrPjLAFhSW7DayE

{
  "title": "Проверкаhccfefveкноевоcwsjhwjw",
  "description": "A year after their fathers funeral, three brothers travel across India by train in an attempt to bond with each other.",
  "genre": "Horror",
  "released": 2019,
  "previewVideoLink": "https://12.react.pages.academy/static/film/video/traffic.mp4",
  "videoLink": "https://12.react.pages.academy/static/film/video/matrix.mp4",
  "starrings": [
        "Owen Wilson",
        "Adrien Brody"
    ],
  "director": "Jemaine Clement",
  "runTime": 2,
  "commentCount": 0,
  "posterImage": "matrix.jpg",
  "backgroundImage": "Once_Upon_a_Time_in_America.jpg",
  "backgroundColor": "#A6B7AC",
  "postDate": "2023-06-09T20:31:26.209Z"
}

###

## Изменить фильм
PATCH http://localhost:5000/films/64838c1e23e2892c5d04a0b8 HTTP/1.1
Content-Type: application/json

{
  "genre": "Documentary"
}

###

## Удалить фильм
DELETE  http://localhost:5000/films/646cfedf24c4a7af9cbcc0ba HTTP/1.1
Content-Type: application/json

###

## Список комментариев к фильму
GET http://localhost:5000/films/6486ef3d116b216841237708/comments HTTP/1.1

###

