## Создать комментарий
POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0ODM1YjU1NGMzODkxZmMwYWY4MWEwOSIsImlhdCI6MTY4Njc2NTY0NSwiZXhwIjoxNjg2OTM4NDQ1fQ.TQMklWB2t61xVzK-rbgMiYQZOqGsLHQUvBBsmYISvao

{
  "text": "Проверка авторизации",
  "filmId": "6486ef3d116b216841237708",
  "rating": 1
}

###

