# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.ch",
  "name": "Jack",
  "password": "123456"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@lost.loca",
  "password": "32456785"
}

###

## Отправить изображение

POST http://localhost:5000/users/6495d9775f81977d52549766/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="0056.jpeg"
Content-Type: image/jpeg

< /Users/gerbe/Pictures/0056.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5jaCIsImlkIjoiNjQ5NWQ5Nzc1ZjgxOTc3ZDUyNTQ5NzY2IiwiaWF0IjoxNjg3Nzg4MTY1LCJleHAiOjE2ODc5NjA5NjV9.7oy60b61ee-bRSowTBYmQawg50aX9dYWmw36oKOAICQ
###
