# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.ch",
  "userName": "Jack",
  "password": "123456"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "president@dka.local",
  "password": "1234567"
}

###

## Отправить изображение

POST http://localhost:5000/users/6491f4743ee80ff08a87a97b/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="0056.jpeg"
Content-Type: image/jpeg

< /Users/gerbe/Pictures/0056.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAbG9zdC5sb2NhIiwiaWQiOiI2NDkxZWI3NzY3N2Q4N2Y0OTQ2NjQ1MmQiLCJpYXQiOjE2ODcyODQ2OTksImV4cCI6MTY4NzQ1NzQ5OX0.tc9P6_EtDMT9oxz-juHyQ9ZHMFpkE7EckmV-GsDGOWM
###
