# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.io",
  "avatarPath": "torrance.png",
  "userName": "Jack",
  "password": "123456"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.io",
  "password": "123456"
}

###

## Отправить изображение

POST http://localhost:5000/users/1/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="0056.jpeg"
Content-Type: image/jpeg

< /Users/gerbe/Pictures/0056.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjY0ODM1YjU1NGMzODkxZmMwYWY4MWEwOSIsImlhdCI6MTY4Njc2NTY0NSwiZXhwIjoxNjg2OTM4NDQ1fQ.TQMklWB2t61xVzK-rbgMiYQZOqGsLHQUvBBsmYISvao
###
